# Generated by Django 5.2.14 on 2026-05-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
