# Generated by Django 5.2.14 on 2026-05-28 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_subscription'),
        ('attendance', '0002_rename_tenant_attendance_institute'),
        ('fees', '0002_rename_tenant_fee_institute'),
        ('students', '0002_rename_tenant_student_institute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenant',
            new_name='Institute',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='tenant',
            new_name='institute',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'institute')},
        ),
    ]
