# Generated by Django 5.2.14 on 2026-05-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_tenant_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
