# Generated by Django 5.2.14 on 2026-06-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetotp_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_verified',
        ),
    ]
