# Generated by Django 5.2.14 on 2026-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_passwordresetotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
