# Generated by Django 5.2.14 on 2026-05-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='tenant',
            new_name='institute',
        ),
    ]
