# Generated by Django 5.2.14 on 2026-07-06 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_tenant_fee_institute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='month',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='fee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
    ]
