# Generated by Django 5.2.14 on 2026-07-06 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_fee_options_fee_created_at_fee_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='fee',
            name='month',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year',
        ),
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
