# Generated by Django 5.2.14 on 2026-07-06 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_fee_options_remove_fee_month_remove_fee_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
